@baseUrl = http://localhost:4000
@companyId = b06cfebb-ff68-4872-8674-511ac047ccc3
@productId = 0f47d82d-98b2-46fa-bafb-0524de07bd45

@managerId = 875b4d2a-dc22-406f-b681-952f610cb2d6
### Criar um novo gerente
POST http://localhost:4000/manager
Content-Type: application/json

{
  "name": "Carlos Souza",
  "email": "carlos.souza@example.com",
  "phone": "11988887777",
  "cpf": "12345678909"
}

### Criar uma nova empresa
POST http://localhost:4000/company
Content-Type: application/json

{
  "name": "Empresa Exemplo",
  "cnpj": "12345678000100",
  "managerId": "{{managerId}}"
}

### Buscar uma empresa por ID
GET http://localhost:4000/company/{{companyId}}

### Listar todas as empresas
GET http://localhost:4000/company

### Atualizar uma empresa
PUT http://localhost:4000/company/{{companyId}}
Content-Type: application/json

{
  "name": "Empresa Atualizada",
  "cnpj": "98765432000100",
  "manager": {
    "name": "Maria Oliveira",
    "email": "maria.oliveira@example.com",
    "phone": "11988888888",
    "cpf": "98765432100"
  }
}

### Deletar uma empresa
DELETE http://localhost:4000/company/{{companyId}}

---

### Criar um novo produto
POST http://localhost:4000/product
Content-Type: application/json

{
  "name": "Produto Exemplo",
  "price": 100.50,
  "description": "Descrição do produto",
  "companyId": "{{companyId}}"
}

### Buscar um produto por ID
GET http://localhost:4000/product/{{productId}}

### Listar todos os produtos
GET http://localhost:4000/product

### Atualizar um produto
PUT http://localhost:4000/product/{{productId}}
Content-Type: application/json

{
  "name": "Produto Atualizado",
  "price": 150.75,
  "description": "Descrição atualizada",
  "companyId": "{{companyId}}"
}

### Deletar um produto
DELETE http://localhost:4000/products/{{productId}}

### Buscar um gerente por ID
GET http://localhost:4000/manager/{{managerId}}

### Listar todos os gerentes
GET http://localhost:4000/manager

### Atualizar um gerente
PUT http://localhost:4000/manager/{{managerId}}
Content-Type: application/json

{
  "name": "Carlos Souza Atualizado",
  "email": "carlos.souza.atualizado@example.com",
  "phone": "11999998888",
  "cpf": "12345678909"
}

### Deletar um gerente
DELETE http://localhost:4000/manager/{{managerId}}